### ISSUE TITLE
countedAudience of Service

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ebucoreplus#207]
CountedAudiences for PublicationEvents and for Campaigns are static results for completed activities. 

For Service, it might be different: Services are not Events (nor limited in time). 
What number should be in the count? From the beginning?, the last year? per day? 

And also for published on-demand content we need to count consumptions right from the beginning of the publication. I think we need a count-per-time structure to collect counts over time. Furthermore, very often the number of consumption events is calculated per time unit **and** per audience (eg. 15000 views of a Youtube-Video between 16:00 and 17:00 on Oct 11 in the targeted audience group of 14 to 19 year old). the count-per-time structure should therefore point to an Audience.

What do you think?

**Comment by tormodv** [comment]
So we need to connect Audience to startDateTime and endDateTime for the counting and start and end of timecode for segments of the media published?

**Comment by JuergenGrupp** [comment]
I don't think we need to count views of segments. And I don't think we should extend Audience with startDateTime and endDateTime. It is not the Audience that starts and ends, it's the counting of ConsumptionEvents. 
How about a class "ConsumptionCount", that holds the number of consumptions from startDateTime to endDateTime and references an EditorialObject and an Audience? This would represent one data point in the measurement of the reach of an eg. a Youtube Video.

**Comment by kimviljanen** [comment]
Good morning! How about instead of "ConsumptionCount", would a better name be for example "ConsumptionEvent" or "ConsumptionStatistics" --- because perhaps "Count" is not all statistics and information we want to collect from the Consumption, but much more?

**Comment by JuergenGrupp** [comment]
I am not opposed to the term ConsumptionStatistic (still prefer ConsumptionCount), but I fear that @kimviljanen's expectations on putting statistical information into the class does not match my proposal. I see the ConsumptionCount as one single data point. Very many of them exist and can be aggregated to create statistical statements. This aggregation can be performed along time (per minute, per hour, per day,  in total ...), along an Audience (14-19 year old, 20-29 year old, over 60, ...). We should not try to represent all possible statistical calculations, but flexible data points. That is why I think it is sufficient ot count the ConsumptionEvents.

**Comment by tormodv** [comment]
> I don't think we need to count views of segments. And I don't think we should extend Audience with startDateTime and endDateTime. It is not the Audience that starts and ends, it's the counting of ConsumptionEvents.
> How about a class "ConsumptionCount", that holds the number of consumptions from startDateTime to endDateTime and references an EditorialObject and an Audience? This would represent one data point in the measurement of the reach of an eg. a Youtube Video.

An audience is a _collection_ of Consumption. We have the Resonance event in the middle, and at the same time, we can divide the audience into different age groups we can _divide_ them on time as well. An on-demand offering will have this many viers this week and this many viers that week.

**Comment by JuergenGrupp** [comment]
> An audience is a collection of Consumption.

I model this as the class "T-Audience". 

I'd rather define : _An audience is a group of potential consumers._
I model this as the class "J-Audience". 

Compare the two options in the following (simplified) sketch:
 
![image](https://user-images.githubusercontent.com/80782611/196549007-9315683e-c744-49ba-a796-e65cad952112.png)

My observations:
- T-Audience:
  - start/end attributes bind each instance of T-Audience to one instance of PublicationEvent
  - every PublicationEvent requires its own T-Audience instance(s) 
  - T-Audience repeats averageAge in every instance (although the same consumers with the same averageAge might be members of T-Audience)
- J-Audience:
  - only ConsumptionCount refers to PublicationEvent, not J-Audience 
  - J-Audience can be described and instantiated independently of PublicationEvents
  - instances of J-Audience can be reused, reflecting existing schemas of potential consumers: e.g. ARD has a „Mediennutzertypologie“, that could be represented as a list of J-Audience instances. The list can be reused in different use cases like offering development, consumption measurement etc. 
![image](https://user-images.githubusercontent.com/80782611/196551879-1c53eadd-589c-4777-963d-27e36657c145.png)

I definitely prefer the J-Audience model. What do you think?

**Comment by tormodv** [comment]
If you by T-Audience mean #213 I must regrettably so say that you have the dissanvantage to be wrong about your statements and usage of the proposed Audience class.

>T-Audience:
start/end attributes bind each instance of T-Audience to one instance of PublicationEvent

No.
Firstly: The range of start and end, as the proposal, very clearly declare, is:
`:start max 1 :TimelinePoint`
They bind to a timeline expressed by a timecode, and this may, not must, be used to describe how the audience count changes throughout the programme. This is a relatively advanced usage, but not more advanced than Facebook and Youtube, which provide this kind of statistics for all their material.
If more course statistics are demanded, the timeline information can be omitted, and the count will be related to one or more publication events. Yes, one or more.
Secondly:
 It is the 
`ebuccdm:hasConsumptionStatistics only ebuccdm:Audience`
is the reference between the PublicationEvent and Audience, not the timeline. There are no restrictions on how many _publicationEvents_ that can refer to the same _Audience_

The direction of the arrow is not significant.

**Simple graph theory: Given node A and B with the edge c there will always be an inverse c' that covers the relationship between node B and C.**

In this way can, the hasConsumptionStatistics be used for collecting data about more than one publication event.

>every PublicationEvent requires its own T-Audience instance(s)

No, not at all. This is not what the graph model describes.

>T-Audience repeats averageAge in every instance (although the same consumers with the same averageAge might be members of T-Audience)

The audience class have no averageAge. The audience class have, on the other hand, the possibility of dividing an audience into different slices on different properties such as age, gender, social standing, etc. The latter is expressed as skos concepts, like the "Mediennutzertypologie".
It seems that the `ebuccdm:includesAudience only ebuccdm:Audience` or the equivalent hasMemberAudience has been overlooked.

If ones have a particular statistics divided on different slices, this can be easily described with the structure ones may
 build with the self relations on the audience class.

![image](https://user-images.githubusercontent.com/12021922/197362739-a616773c-b0b1-4207-8e09-38ce68bf4d80.png)

For the second group of bullet points, there are no concepts that can't be expressed by the proposal.

**Comment by tormodv** [comment]
Can we close this issue?
