### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by saerdnaer** [ebu/ebucoreplus#258]
Is there any reason why the diagram from today's presentation is not included in the readme to describe the project's vision?

**Comment by JuergenGrupp** [comment]
Thank you, @saerdnaer for pointing this out! We're currently working on documentation issues and this diagram might indeed be helpful:
![image](https://user-images.githubusercontent.com/80782611/224357301-f5cff608-03c7-4ee8-8654-43356df428a6.png)

**Comment by JuergenGrupp** [comment]
The README file was reviewed and updated. However, the diagram above did not make it to the latest edition because the Editorial Committee wanted to focus on the overview of the class structure of EBUCorePlus.
