### ISSUE TITLE
Versioning the IRIs

### ISSUE THREAD

**Issue by kimviljanen** [ebu/ebucoreplus#269]
Random thought: I just noticed there is no versioning information in the IRIs, which is quite typical in APIs etc: “http://www.ebu.ch/metadata/ontologies/ebucoreplus-v1#EditorialObject“ (v1 added by me). ==>> Question: So if the definition of e.g. EditorialObject changes, how do you handle the situations where you have data refering to both new and old definition?

**Comment by aro-max** [comment]
We manage ontology versions as follows: 
- in the .owl file, the version is indicated as follows:  
--> owl:versionIRI <http://www.ebu.ch/metadata/ontologies/ebucoreplus/1.0.0> 

- in Github, the official versions are tagged for instance the v1.0.0 is available there:
-->https://github.com/ebu/ebucoreplus/releases/tag/v1.0.0

In this way, a developer can download the official versions of EBUCoreplus via the GitHub tag and the version name is also present in the .owl file.

When deploying the ontology via an API, the version should be encoded in the request to make it visible to the user. This is managed at the implementation level, not the specification level.

**Comment by JuergenGrupp** [comment]
Closed issue, following up on discussion above.
