### ISSUE TITLE
Questionable implementation of "promotes" for EditorialWork and Trailer

### ISSUE THREAD

**Issue by alexander-schulze** [ebu/ebucoreplus#273]
The class "Trailer" promotes "only" Editorial group" and also "Editorial work".
Semantically, this is inconsistent, since as two statements this is contractictory:

![grafik](https://github.com/ebu/ebucoreplus/assets/298558/94fff098-4b99-41a6-ac05-efdf96edf0fb)

Alternatively, this could be modelled using an "or"'d restriction, like:
![grafik](https://github.com/ebu/ebucoreplus/assets/298558/d52cfb41-a5fb-44a5-8b1d-198d2da95172)

Also, the class Editorial Work already declares "promotes Editorial work", which would be inherited to "Trailer".
However, the class "Trailer" declares that redundantly:

EditorialWork:
```
###  http://www.ebu.ch/metadata/ontologies/ebucoreplus#EditorialWork
ec:EditorialWork rdf:type owl:Class ;
                 rdfs:subClassOf ec:EditorialObject ,
                                 [ rdf:type owl:Restriction ;
                                   owl:onProperty ec:hasEditorialGroup ;
                                   owl:allValuesFrom ec:EditorialGroup
                                 ] ,
                                 [ rdf:type owl:Restriction ;
                                   owl:onProperty ec:hasEditorialWork ;
                                   owl:allValuesFrom ec:EditorialWork
                                 ] ,
                                 [ rdf:type owl:Restriction ;
                                   owl:onProperty ec:promotes ;
                                   owl:allValuesFrom ec:EditorialWork
                                 ] ;

```

Trailer:
```
###  http://www.ebu.ch/metadata/ontologies/ebucoreplus#Trailer
ec:Trailer rdf:type owl:Class ;
           rdfs:subClassOf ec:EditorialWork ,
                           [ rdf:type owl:Restriction ;
                             owl:onProperty ec:promotes ;
                             owl:allValuesFrom ec:EditorialGroup
                           ] ,
                           [ rdf:type owl:Restriction ;
                             owl:onProperty ec:promotes ;
                             owl:allValuesFrom ec:EditorialWork
                           ] ;
```

Thanks to Stefan Kollien here, who detected that during his app implementation.

**Comment by JuergenGrupp** [comment]
Thank you, @alexander-schulze , for documenting this.
Obviously, the inconsistent use of ´promotes´ was introduced together with the class hierarchy of ´Trailer´. It is still true, that ´EditorialWork´ promotes ´EditorialWork´ or ´EditorialGroup´. ´Trailer´ is just a subclass of ´EditorialWork´ and can inherit the property ´promotes´.  Therefore the proposal is:

- remove the 2 ´promotes´ class restrictions from ´Trailer´
- make ´promotes´ a class restriction of ´EditorialWork´ for ´EditorialGroup´ OR ´EditorialWork´

Pull request will follow.
