### ISSUE TITLE
How can the start and end date and/or the duration of a production be represented?

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ebucoreplus#279]
Some productions span over months or years. It can be neccessary to document this either for planning purposes (especially the duration which impacts the cost) or for documentation purposes (think of a season of a series that might take several months to complete the episodes)

Do we need a `startDateTime`, `endDateTime` and `duration` property in the class `ProuctionJob`?

**Comment by tormodv** [comment]
Good idea! 
startDateTime and  endDateTime should be suficient.
