### ISSUE TITLE
An EditorialObject may have a target audience and a target platform, but should also have a target channel or target service

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ebucoreplus#280]
If a video is planned and produced for a Youtube-channel, its EditorialObject should be able to represent not only a target audience or target platform, but also mor specifically a target channel and a target service. I propose to introduce these object properties for the class EditorialObject:

1. `hasTargetService` `PublicationService`
2. `hasTargetChannel` `PublicationChannel`

**Comment by tormodv** [comment]
Yes, we can do that or go for the more generic hasTarget. If we should change hasTargetAudience as well, this will be a more significant change. 
So:
hasTargetService PublicationService
hasTargetChannel PublicationChannel
seems like the easiest solution.
