### ISSUE TITLE
Remove ebucore.rdf file from repository

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ebucoreplus#321]
The file ebucoreplus/ontology/EBUCorePlus/ebucore.rdf is outdated and not maintained any further. After the merge of CCDM and ebucore, we only continue development based on ebucoreplus.owl. I propose to remove ebucore.rdf from the repository.

**Comment by MarcAntoine-Arnaud** [comment]
@JuergenGrupp you may close the issue as it's merged.
