### ISSUE TITLE
Double representation of Subtitling and Captioning

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ebucoreplus#327]
There are two representations of the fact that subtitles are present:
One is through `Subtitling` and its subclasses and another one is through `Captioning` and its subclasses.
![image](https://github.com/ebu/ebucoreplus/assets/80782611/7da0f930-f00a-4e90-aabf-c07e058f043b)

We need to examine, which of them should survive and which should be removed.

**Comment by MatthieuParme** [comment]
I do underline Marc-Antoine’s comment, only a few people knows, most use « subtitles for hard of hearing audience » instead of « captions » even it is definitely shorter and more convenient.

**Comment by JuergenGrupp** [comment]
Ok, thank you, @MarcAntoine-Arnaud and @MatthieuParme,  for pointing out the differences of captions and subtitles. 
I close the issue.
