### ISSUE TITLE
Questions regarding ebucoreplus

### ISSUE THREAD

**Issue by RendersKoen** [ebu/ebucoreplus#348]
Hi all, I got some questions regarding interpretation of classes and properties... I'm not sure if this is the right place to post them... let me know!

For example: http://www.ebu.ch/metadata/ontologies/ebucoreplus#Event

Looking at the subclasses, I suppose this should be interpreted more as an "occurence" in wikidata https://www.wikidata.org/wiki/Q1190554 than as an "event" https://www.wikidata.org/wiki/Q1656682

And there is no such class as a "planned" event yet (like festivals or a public broadcasting event)?

I might of course be missing or misunderstanding something :-)

**Comment by JuergenGrupp** [comment]
I think the http://www.ebu.ch/metadata/ontologies/ebucoreplus#Event does not really distinguish between the two, i.e. it can be used for both. It has a start time and an end time and a location, which allows it to represent wikidata "occurences" https://www.wikidata.org/wiki/Q1190554. 
And it can have an identifier, which probably makes it applicable also for wikidata "events" https://www.wikidata.org/wiki/Q1656682) and for "planned events" like a concert or a sports tournament.

Further questions are always welcome, but maybe their better placed in a list and directed towards the EBU-coordinator of the metadata modelling group (https://tech.ebu.ch/groups/mm)? Where would you expect to find the answers? 
I could reuse the questions for a FAQ section in the documentation, eg. the wiki.

**Comment by JuergenGrupp** [comment]
Hi @RendersKoen , please indicate whether the answer is satisfying or not. I could then close the issue. Thank you!

**Comment by RendersKoen** [comment]
Yes thanks Juergen, excuse me for not having replied earlier!
